version: "3.9"
services:
  mariadb:
    build: ./requirements/mariadb/
    image: mariadb
    container_name: mariadb
    restart: on-failure
  nginx:
    build: ./requirements/nginx/
    image: nginx
    container_name: nginx
    init: true
    ports:
      - 7780:80
      - 443:443
    restart: on-failure
    networks:
      - vikka
  wordpress:
    build: ./requirements/wordpress/
    image: wordpress
    container_name: wordpress
    init: true
    restart: on-failure
    networks:
      - vikka

networks:
  vikka:
    driver: bridge 
  artur:
    driver: bridge

